/* 
 * Copyright 2017 Federal Highway Administration.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package imrcp.store;

import imrcp.system.Introsort;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;

/**
 * The file wrapper for files generated by the Bayes package
 */
public class BayesCsv extends CsvWrapper
{

	/**
	 * Loads the file into memory
	 *
	 * @param lStartTime the time the file starts being valid
	 * @param lEndTime the time the file stops being valid
	 * @param sFilename absolute path of the file to load
	 * @throws Exception
	 */
	@Override
	public void load(long lStartTime, long lEndTime, String sFilename) throws Exception
	{
		String sLine;
		m_oCsvFile = new BufferedReader(new InputStreamReader(new FileInputStream(sFilename)));
		sLine = m_oCsvFile.readLine(); // skip header

		if (m_oCsvFile.ready())
		{
			synchronized (m_oObs)
			{
				m_oObs.clear();
				while ((sLine = m_oCsvFile.readLine()) != null)
					m_oObs.add(new Obs(sLine));
			}
		}
		m_oCsvFile.close();

		synchronized (m_oObs)
		{
			Introsort.usort(m_oObs, Obs.g_oCompObsByTime);
		}
		m_lStartTime = lStartTime;
		m_lEndTime = lEndTime;
		m_sFilename = sFilename;
	}


	/**
	 * Cleans up resources and deletes the file because we are not storing old
	 * Bayes files
	 */
	@Override
	public void cleanup()
	{
		try
		{
			if (m_oCsvFile != null)
				m_oCsvFile.close();
			File oFile = new File(m_sFilename);
			if (oFile.exists())
				oFile.delete();
			m_oObs.clear();
		}
		catch (Exception oException)
		{
			m_oLogger.error(oException, oException);
		}
	}
}
