/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imrcp_geosrv_GeoUtil */

#ifndef _Included_imrcp_geosrv_GeoUtil
#define _Included_imrcp_geosrv_GeoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    makeBox
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_imrcp_geosrv_GeoUtil_makeBox
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    makePolygon
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_imrcp_geosrv_GeoUtil_makePolygon
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    clipBox
 * Signature: ([I[J)I
 */
JNIEXPORT jint JNICALL Java_imrcp_geosrv_GeoUtil_clipBox
  (JNIEnv *, jclass, jintArray, jlongArray);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    clipPolygon
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_imrcp_geosrv_GeoUtil_clipPolygon
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    popResult
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_imrcp_geosrv_GeoUtil_popResult
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    freeBox
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imrcp_geosrv_GeoUtil_freeBox
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imrcp_geosrv_GeoUtil
 * Method:    freePolygon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imrcp_geosrv_GeoUtil_freePolygon
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
