/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imrcp_system_XzBuffer */

#ifndef _Included_imrcp_system_XzBuffer
#define _Included_imrcp_system_XzBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imrcp_system_XzBuffer
 * Method:    init
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_imrcp_system_XzBuffer_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imrcp_system_XzBuffer
 * Method:    proc
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_imrcp_system_XzBuffer_proc
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     imrcp_system_XzBuffer
 * Method:    free
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_imrcp_system_XzBuffer_free
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
